name: 同步coolsnowwolf-lede仓库
on:
  schedule:
    - cron: 26 6 * * *
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-coolsnowwolf-lede
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync coolsnowwolf-lede
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/coolsnowwolf/lede.git"
          source_branch: "master"
          destination_branch: "lede"
          github_token: ${{ secrets.PAT }}
