name: 同步P3TERX-Actions-OpenWrt仓库
on:
  schedule:
    - cron: 38 8 * * *
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-P3TERX-Actions-OpenWrt
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync P3TERX-Actions-OpenWrt
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/P3TERX/Actions-OpenWrt.git"
          source_branch: "main"
          destination_branch: "P3TERX"
          github_token: ${{ secrets.PAT }}
